name: Azure Site Recovery
on:
  workflow_dispatch:
    inputs:
      Subscription:
        type: choice
        description: "Please select Source Subscription"
        options:
          - sub-jda-cld-solutions-01
          - sub-by-cld-solutions-ase-02
          - sub-by-cld-solutions-aue-02
          - sub-by-cld-solutions-eus2-02
          - sub-by-cld-solutions-euw-02
        required: true

      ResourceGroup:
        description: "Provide Source Resource Group"
        required: true
    
     

env:
  SOURCE_SUBSCRIPTION: "${{ github.event.inputs.Subscription }}"
  SOURCE_RESOURCEGROUP: "${{ github.event.inputs.ResourceGroup }}"
  REQUESTOREMAIL: "${{ github.event.inputs.requestor }}"
 
jobs:
  GET_DETAILS_FROM_AZURE:
    
    runs-on: ubuntu-latest
    outputs:
      AR: ${{ steps.RG.outputs.ar }}
    steps:
      - uses: actions/checkout@v2
      
      - name: " Validate the core components in RG "
        id: RG
        uses: azure/powershell@v1
        with:
          azPSVersion: "latest"
          inlineScript: |
            
            $a = 2
            if ($a -eq '2') {
              $ar = "ashok"    }
             echo "::set-output name=ar::$ar"

  GET_DETAILS_FROM_DB:
    runs-on: ubuntu-latest
    needs: [GET_DETAILS_FROM_AZURE]
 
    steps:
      - uses: actions/checkout@v2
      
      - name: "source subscription is equal to target subscription"
        run:
            echo "${{ needs.GET_DETAILS_FROM_AZURE.outputs.AR }}"
  
  
  GET_DETAILS_FROM_APP:
    runs-on: ubuntu-latest
    needs: [GET_DETAILS_FROM_DB]
  
 
    steps:
      - uses: actions/checkout@v2
      
      - name: "source subscription is equal to target subscription"
        run:
            echo "HelloWord3"
            echo "${{ GET_DETAILS_FROM_AZURE.outputs.AR }}"
 
        
